hanxiao:
  db:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&characterEncoding=utf-8
#    username: root
#    password: 123465

mybatis:
  type-aliases-package: com.hanxiao.springboot2.bean
